plugins {
    id 'com.android.library'
    id 'kotlin-android'
    alias libs.plugins.compose.compiler
}

android {
    namespace "dev.sanson.donezo.backend"

    compileSdkVersion libs.versions.compilesdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minsdk.get().toInteger()
        targetSdkVersion libs.versions.targetsdk.get().toInteger()
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    api project(":model")

    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    implementation libs.kotlinx.coroutines.core

    coreLibraryDesugaring libs.corelibrarydesugaring
}
