[versions]
# App Versions
app = "0.0"
versioncode = "1"

# Android build specifications
minsdk = "24"
compilesdk = "35"
targetsdk = "35"

# Libraries
compose-bom = "2025.04.00"

kotlin = "2.1.20"
android-gradle-plugin = "8.9.1"

androidx-core-ktx = "1.16.0"
androidx-activity-compose = "1.10.1"
androidx-lifecycle = "2.8.7"
androidx-datastore = "1.1.0"

core-library-desugaring = "2.1.5"

kotlinx-coroutines = "1.10.2"
kotlinx-collections-immutable = "0.3.8"
kotlinx-serialization-json = "1.8.1"

reduxkotlin = "0.6.1"

koin = "4.0.4"

junit = "4.13.2"
kotest = "5.9.1"
test-parameter-injector = "1.18"

material = "1.12.0"

spotless = "7.0.3"
ktlint = "1.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

corelibrarydesugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "core-library-desugaring" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
datastore = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }

redux = { module = "org.reduxkotlin:redux-kotlin-threadsafe-jvm", version.ref = "reduxkotlin" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm", version.ref = "kotlinx-collections-immutable" }

junit = { module = "junit:junit", version.ref = "junit" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
test-parameter-injector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "test-parameter-injector" }


[bundles]
compose = [
    "androidx-compose-runtime",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
]

# Standard lifecycle libraries which are useful in Android
lifecycle = ["lifecycle-runtime", "lifecycle-livedata", "lifecycle-viewmodel-compose"]

# Useful unit testing dependencies
unittesting = [ "junit", "kotest-assertions", "kotlinx-coroutines-test", "test-parameter-injector" ]
